### ISSUE TITLE
Rendering - control to big for 3 collumns section

### ISSUE THREAD

**Issue by WouterKessener** [drivardxrm/FluentUI.Slider.PCF#2]
Browser at 100% - Not oke

![Slider Fluent 100%](https://github.com/drivardxrm/FluentUI.Slider.PCF/assets/15956643/f95a56f9-1c71-4ce6-921b-09eefb68f930)

Browser at 100 - As it should be :-) but at 100%

![Slider Fluent 80%](https://github.com/drivardxrm/FluentUI.Slider.PCF/assets/15956643/3f9dd0e8-2d7c-456e-b6a3-0b780c193fe1)

**Comment by drivardxrm** [comment]
thanks @WouterKessener ,
I will look into this

**Comment by drivardxrm** [comment]
Hi @WouterKessener,

I have fixe the issue in the lest release v1.0.0.6

Now, when there is not enough space to render the control,
the objects will overflow on top of the slider. (I tried several combination and this was the best looking solution)

![image](https://github.com/drivardxrm/FluentUI.Slider.PCF/assets/38399134/5e2be815-3d7a-4d85-b95b-5937634ae420)

Hope you like it.

**Comment by WouterKessener** [comment]
@drivardxrm you are amazing. Thanks so much. Tested it: works great

![Fluetn Slider Solved](https://github.com/drivardxrm/FluentUI.Slider.PCF/assets/15956643/f8e19d92-7974-44c0-bb3d-7360635a0f90)
