### ISSUE TITLE
Control enables changes to fields on Inactive Records, or when field is set to Read Only

### ISSUE THREAD

**Issue by hymans-ryanmaclean** [drivardxrm/FluentUI.Slider.PCF#4]
The slider allows me to edit the values in a field even when the record is set to Inactive, or when I set the field to be Read Only

![image](https://github.com/drivardxrm/FluentUI.Slider.PCF/assets/104084324/73f56acd-4ddc-4f34-a202-e2c152d1d540)

Is there any way to fix this? 

Thanks,

Ryan

**Comment by drivardxrm** [comment]
Hi @hymans-ryanmaclean,

I was sure that this was taken into considerations.

Let me have a look
(might take a week or 2, I'm pretty busy these days)

Thanks for your feedback

**Comment by drivardxrm** [comment]
Hi @hymans-ryanmaclean ,
I have released a new version that fixed the issue.
https://github.com/drivardxrm/FluentUI.Slider.PCF/releases/tag/v1.0.0.8

Tell me if it works,

**Comment by hymans-ryanmaclean** [comment]
Hey David, thanks for such a speedy reply.  I've imported the new release and it's working now

I really appreciate how quickly you turned this around!
